spring:
  application:
    name: analytics

  datasource:
    url: jdbc:postgresql://analytics_db:5432/mydatabase
    username: myuser
    password: secret

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    consumer:
      group-id: consumer-monitoring-group
      bootstrap-servers: localhost:9092

server:
  port: 8084