spring:
  application:
    name: customer_relationship_management
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: jdbc:postgresql://postgres:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  kafka.consumer:
     bootstrap-servers: kafka:9092
     group-id: consumer
     auto-offset-reset: earliest

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9095/realms/kc1
keycloak:
  server-url: http://localhost:9095
  realm: kc1
  client-id: kc1client
  client-secret: A4PGV1WAVvB528I2rCXsY00Bv2JMAERW
server:
  port: 8050


