//run after al least an upload document to test the correct response
GET http://localhost:8080/documents/1

###
//run after al least an upload document to test the DocumentNotFoundException
GET http://localhost:8080/documents/9999